spring:
  application:
    name: graphql-java-intro
#  servlet:
#    multipart:
#      enabled: true
#      location: /tmp

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

#graphiql:
#  enabled: true
#  cdn:
#    enabled: false

#voyager:
#  enabled: true
#  cdn:
#    enabled: false